# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenRtkQuery < Formula
  desc "Generate rtk query endpoints from grpc service definitions"
  homepage "https://github.com/greatliontech/protoc-gen-rtk-query"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.2.1/protoc-gen-rtk-query_0.2.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e653a2a99c10eef4660d9feb4a7b5acc4b35d703592571f81cc5befa1715e914"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.2.1/protoc-gen-rtk-query_0.2.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c4a71b513da85a3104b8e28312cbed67deb558679950d766c259cbd84c506b2"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.2.1/protoc-gen-rtk-query_0.2.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ad310f7c5566f532c44f7fc3b15d3eaaae284171acaf217cc42d8f4d009b1df0"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/protoc-gen-rtk-query/releases/download/0.2.1/protoc-gen-rtk-query_0.2.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cea9e03e6e6b0656e885c0ffbc2495f57ce9035620cbf78dab8c665ad74cc73e"

      def install
        bin.install "protoc-gen-rtk-query"
      end
    end
  end
end
