# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semrel < Formula
  desc "Semantic Versioning and Conventional Commits release utility"
  homepage "https://github.com/greatliontech/semrel"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.0/semrel_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6401ee5f0da888376075b51ec8aaa42dff631e9809ed663916b189bee86e138d"

      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.0/semrel_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "684a9dd917d91bfcefacba6eff3ef4bee68317a6e210f88ab076a4fa8d1aa5aa"

      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.0/semrel_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "c2e81e7ae3d168e4a37d19e1396639516496b25330589b6f2942cbb804d49b2c"
      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.0/semrel_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8e69c7ba9da63179a36c1bf1631040e1f58539c75b24818e7c98ba5ac0b156a1"
      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
  end
end
