# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semrel < Formula
  desc "Semantic Versioning and Conventional Commits release utility"
  homepage "https://github.com/greatliontech/semrel"
  version "0.4.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.6/semrel_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "4a964560c8801437ec9b172141aa206b34cf115551f1bd39abee93fdd7de2ce2"

      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.6/semrel_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "666d5c5ba7343228bf553fc88c994b61bb82c901804e0afc0a8775ab2469dd26"

      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.6/semrel_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9edddde49bdb0bb34e9279433342784b0cc1f6a1b36e6643328fd44238ed548d"
      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/semrel/releases/download/0.4.6/semrel_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "09dddcdb40e25cd5d6dacfed824ea3bc5561e2a828a32cc0da530a9f4587f9c4"
      def install
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
  end
end
