# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Semrel < Formula
  desc "Semantic Versioning and Conventional Commits release utility"
  homepage "https://github.com/greatliontech/semrel"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/greatliontech/semrel/releases/download/0.7.0/semrel_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b42e3abcd87e17d9d57c493e6de4db888436d179c25e666d92e56f1e1fd445f1"

      define_method(:install) do
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/greatliontech/semrel/releases/download/0.7.0/semrel_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c177f524c6dd58ac9093a616b289658b3a34e6abba1920e0f6859433feb91f69"

      define_method(:install) do
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/semrel/releases/download/0.7.0/semrel_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "419845e91ac10318df258500c59b224ed9a43910ac7078c50a5fef9d61ca9500"
      define_method(:install) do
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/greatliontech/semrel/releases/download/0.7.0/semrel_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "563c5205613ea3b4325bb220d3bd506db4f18094c42b2332ffde2cf47e23391b"
      define_method(:install) do
        bin.install "semrel"
        bash_completion.install "completions/semrel.bash" => "semrel"
        zsh_completion.install "completions/semrel.zsh" => "_semrel"
        fish_completion.install "completions/semrel.fish"
      end
    end
  end
end
